name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*


env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/rapier

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      # build multi-arch image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: . 
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source= ${{ github.repository }}
            org.opencontainers.image.revision= ${{ github.sha }}
            org.opencontainers.image.created= ${{ steps.build-and-push.outputs.image_created }}
            org.opencontainers.image.version= ${{ github.sha }} 
  